@startuml template

!include ./defines.puml

Person_Ext(anonymous_user, "external user", $tags="no_user")
Person(aggregated_user, "André, Thiago", $tags="user")
Person(administration_user, "admin", $tags="admin")

System_Boundary(c1, "template.js"){
    Container(web_app, "Web Application", " Svelte, go ", $tags="web_app")
    ContainerDb(rel_db, "Relational Database", "PostgreSQL", $tags="db", $sprite="postgresql")
    Container(filesystem, "File System", "FAT32", $tags="files")
    ContainerDb(nosql, "NoSQL", "MongoDB 2.2.x", $tags="db")
    Container(ms1, "Service API's", " node.js ", $tags="microservice")
    Container(updater, "Updater", " bash script ", $tags="con_app")
}

Rel(anonymous_user, web_app, "Uses", "HTTPS", $tags="firewall")
Rel(aggregated_user, web_app, "Uses", "HTTPS", $tags="firewall")
Rel(administration_user, web_app, "Uses", "HTTPS", $tags="firewall")

Rel(web_app, rel_db, "Reads / writes to", "SQL/JDBC, port 5432")
Rel(web_app, filesystem, "Reads from")
Rel(web_app, nosql, "Reads from", "MongoDB wire protocol, port 27017")

Rel_R(updater, ms1, "consumes")
Rel_U(updater, rel_db, "Reads / writes to", "SQL/JDBC, port 5432")
Rel_U(updater, filesystem, "Writes to")
Rel_U(ms1, nosql, "Reads from and writes to", "MongoDB wire protocol, port 27017")

Lay_R(rel_db, filesystem)

SHOW_LEGEND()
@enduml